### ISSUE TITLE
Update lockfile to automatically remove the vulnerability introduced in oas-normalize

### ISSUE THREAD

**Issue by paimon0715** [readmeio/oas-normalize#148]
Hi, @erunion, I have reported a vulnerability issue in package **z-schema**.

As far as I am aware, vulnerability [**SNYK-JS-VALIDATOR-1090600**](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090600),  [**SNYK-JS-VALIDATOR-1090599**](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090599), [**SNYK-JS-VALIDATOR-1090602**](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090602) and [**SNYK-JS-VALIDATOR-1090601**](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090601) detected in package **validator(<13.6.0)** is directly referenced by  **z-schema@4.2.3**, on which your package **oas-normalize@3.0.4** transitively depends. As such, this vulnerability can also affect **oas-normalize@3.0.4** via the following path:
`oas-normalize@3.0.4 ➔ swagger-parser@10.0.2 ➔ @apidevtools/swagger-parser@10.0.2 ➔ z-schema@4.2.3 ➔ validator@12.2.0(vulnerable version)`

Since **z-schema** has released a new patched version **z-schema@4.2.4** to resolve this issue (**z-schema@4.2.4 ➔ validator@13.6.0(fix version)**), then this vulnerability patch can be automatically propagated into your project only if you **update your lockfile**. The following is your **new dependency path** :
`oas-normalize@3.0.4 ➔ swagger-parser@10.0.2 ➔ @apidevtools/swagger-parser@10.0.2 ➔ z-schema@4.2.4 ➔ validator@13.6.0(vulnerability fix version)`.

A warm tip.
Best regards,
^_^

**Comment by erunion** [comment]
Thanks for the heads up, this looks to be resolved with https://github.com/readmeio/oas-normalize/pull/151. I'll publish a release in a bit.

```
$ npm ls validator
oas-normalize@3.0.4 /Users/erunion/code/readmeio/oas-normalize
└─┬ swagger-parser@10.0.3
  └─┬ @apidevtools/swagger-parser@10.0.3
    └─┬ z-schema@5.0.1
      └── validator@13.6.0
```
