### ISSUE TITLE
Getting errors with using oas with typescript

### ISSUE THREAD

**Issue by ishaan812** [readmeio/oas-normalize#275]
This is the error i'm getting when trying to use it in the same way as the basic usage in the readme file.

This expression is not constructable.
  Type 'typeof import("c:/GSOC/Github-OpenAPI-Search/node_modules/oas-normalize/dist/index")' has no construct signatures.ts(2351)

**Comment by ishaan812** [comment]
Eh nvm, used 
const oas = new OASNormalize.default(content); to fix the error.
But maybe this can be added to the README. Cheers!

**Comment by erunion** [comment]
How are you importing the library? `import OASNormalize from 'oas-normalize';` should work just fine and allow you to do `new OASNormalize()`.

**Comment by ishaan812** [comment]
Wasnt working for me, for some rreason was working with OASNormalize.default though.

**Comment by erunion** [comment]
Mind sharing your `tsconfig` file?
