### ISSUE TITLE
Trouble running the first example

### ISSUE THREAD

**Issue by edrandall** [readmeio/oas-normalize#281]
I'm not familiar with node, just wanted a tool that can normalize and validate swagger.json files.
I cannot figure out what I am supposed to do to run the first example.
I set up as follows:
1. `npm install oas-normalize`
this seemed to complete successfully:
```
added 87 packages, and audited 88 packages in 11s

found 0 vulnerabilities
npm notice
npm notice New major version of npm available! 8.19.4 -> 9.7.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.7.2
npm notice Run npm install -g npm@9.7.2 to update!
npm notice
```

2. I have a local file `swagger.json` which I want to check so I copied the example code into a local file named `normalize.js` and edited to reference that file:
```

import OASNormalize from 'oas-normalize';
// const { default: OASNormalize } = require('oas-normalize'); // If you're using CJS.

const oas = new OASNormalize(
  'swagger.json'
  // ...or a string, path, JSON blob, whatever you've got.
);

oas
  .validate()
  .then(definition => {
    // Definition will always be JSON, and valid.
    console.log(definition);
  })
  .catch(err => {
    console.log(err);
  });
  ```
  
  3. Run using node (I have v16.20.0 installed):
  ```
   $ node normalize.js
(node:79739) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/erandall/Workspace/_foresight/apps/metadata-service/normalize.js:2
import OASNormalize from 'oas-normalize';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

4. Tried to fix that by creating a `package.json` per another s/o answer:
```
{
  "type": "module"
}
```

```
$ node normalize.js
file:///Users/erandall/Workspace/_foresight/apps/metadata-service/normalize/normalize.js:5
const oas = new OASNormalize(
            ^

TypeError: OASNormalize is not a constructor
```

Please help, what do I need to do to run this thing? 
Perhaps you could provide a shell script to do any additional steps needed to launch it correctly?

**Comment by edrandall** [comment]
renamed `normalize.js` to `normalize.cjs`.
Added a shebang, switched to using the 'CJS' require line instead.
```
#!/usr/bin/env node

// import OASNormalize from 'oas-normalize';
const { default: OASNormalize } = require('oas-normalize'); // If you're using CJS.
```
Now getting close...
```
$ ./normalize.cjs
Error: Use `opts.enablePaths` to enable accessing local files.
```

**Comment by edrandall** [comment]
Changed the constructor call to
```
const oas = new OASNormalize( 'swagger.json', { enablePaths: true } );
```
Now able to run it successfully.


What I need is a command which will normalize different swagger.json files such that they can be successfully compared using tools such as `diff`.   The files I have, are mostly the same, but the odd field is different.   Unfortunately endpoint parameters are getting output in an arbitrary order and comparison has become extremely difficult.

**Comment by domharrington** [comment]
Hey! Thanks for posting in here, your first few comments are an unfortunate chain of events if you're not familiar with node. Node by default uses CJS (Common JS) but is in a weird transitionary period moving over to ESM modules. It's all a bit of a mess at the moment but I'm glad you got through it!

Regarding `opts.enablePaths` being off by default, @erunion can probably chime in more here but I'm guessing this is for security reasons. 

Your issue with the objects being abbreviated is just how `console.log` works by default in Node, it only prints out objects a few levels deep. You can fix this by doing one of two things:

1. Print JSON to the console
You can do this using:

```js
console.log(JSON.stringify(definition))
```

If you want nesting, you can use the [`space` parameter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#parameters):


```js
console.log(JSON.stringify(definition, null, 2))
```

Outputting to JSON will allow you to use `diff` et al on it. If you wanna stay in Node, you could also use [`assert.deepStrictEqual()`](https://nodejs.org/api/assert.html#assertdeepstrictequalactual-expected-message) and it'll give you a pretty diff.

2. Use `util.inspect` if you want something thats a little prettier, but not valid JSON

```js
console.log(require('util').inspect(definition, { depth: null }))`
```

https://nodejs.org/api/util.html#utilinspectobject-options

---------------

Object keys are not sorted by default in JS, and I suspect we're not changing their order which means we're likely showing you them in the order they're defined in the file. I'll leave it as an exercise for you to sort them, but using something like [this](https://stackoverflow.com/a/31102605) should do the trick!

I hope that helps!

**Comment by erunion** [comment]
> Regarding `opts.enablePaths` being off by default, @erunion can probably chime in more here but I'm guessing this is for security reasons.

This is correct!
